### ISSUE TITLE
Add option for setting the (coq)extra-dev opam repo?

### ISSUE THREAD

**Issue by erikmd** [coq-community/docker-coq-action#19]
adding a line such as [this one](https://github.com/coq-community/templates/blob/61a98842f9cadf519b901a12b17b782d65e03118/.travis.yml.mustache#L17)

@Zimmi48 what do you think? − do you have some YAML field name suggestion?

**Comment by Zimmi48** [comment]
It looks to me like the use case would be superseded the solution currently discussed for #22. WDYT?

**Comment by erikmd** [comment]
@Zimmi48 indeed, if https://github.com/coq-community/docker-coq-action/issues/22#issuecomment-695803544 can be implemented, this feature will just be some instance, with a code such as:

```
- uses: coq-community/docker-coq-action@v1
  with:
    before_install: |
      opam repo add --all-switches --set-default coq-extra-dev https://coq.inria.fr/opam/extra-dev
      opam repo list
```

so, closing this issue as a duplicate of #22
