### ISSUE TITLE
[wish] running extra code after build (but before uninstall)

### ISSUE THREAD

**Issue by gares** [coq-community/docker-coq-action#25]
My use case is that I'd like to build my package, and then use my package to build other packages, to see if I break my clients.

Ideally, I'd like to be able to use `actions/(upload|download)-artifact@v2` to have multiple jobs, but I've no idea if this is OK with docker.

Alternatively, I'd like to run some commands before opam remove, and today I've to override the entire script, which is not super nice.

Any thoughts?

**Comment by Zimmi48** [comment]
Related: #18

**Comment by erikmd** [comment]
also related to: https://github.com/coq-community/docker-coq-action/issues/22#issuecomment-674528578

**Comment by erikmd** [comment]
Hi @gares, thanks for opening this (and sorry for the delay); several remarks:

1. it is already possible to customize the script (see the doc of the [`custom_script` field](https://github.com/coq-community/docker-coq-action/#custom_script)) and add some custom bash commands (not actions) before the uninstall step.
    By the way did you think about using `actions/upload-artifact` or so to push the `.opam` folder? or another directory/files?

2. it is also possible to keep generated artifacts from the (isolated) container build available from the subsequent jobs steps, **provided** you put them in the initial working directory `/github/workspace` (the root of the ambient git repo).
    You can find an example of this approach in [this Zulip thread](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/CI.20docker.20images.3F/near/210667857) opened by @JasonGross or in this repo:
    https://github.com/erikmd/docker-run-github-workflow-example/blob/master/.github/workflows/test.yml

3. Approach 1. above could be ultimately simplified by adding an option `before_uninstall_script`, similarly to the `before_install_script` that @liyishuai mentioned in https://github.com/coq-community/docker-coq-action/issues/22#issuecomment-674528578; but implementing this does not seem straightforward… I'll comment further in #22 though.
