### ISSUE TITLE
Issue: latest release `v1.1.0` is not yet in the GitHub Actions marketplace

### ISSUE THREAD

**Issue by erikmd** [coq-community/docker-coq-action#28]
Hi @Zimmi48, I re-checked the page https://github.com/marketplace/actions/docker-coq-action and the latest release is not there, so I opened https://github.com/coq-community/docker-coq-action/releases/edit/v1.1.0 and I see:

* [ ] Publish this release to the GitHub Marketplace
`coq-community must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.`

can you see if you have the rights to [check that box](https://github.com/coq-community/docker-coq-action/releases/edit/v1.1.0)?

**Comment by Zimmi48** [comment]
Done!
