### ISSUE TITLE
after_script cannot contain '

### ISSUE THREAD

**Issue by gares** [coq-community/docker-coq-action#40]
Apparently something goes wrong with the shell fiddling, and you get an error like "the expanded script is empty".
Removing `'` from the script solves the problem.

FTR, this reproduces the bug:
```
        after_script: |
          startGroup "Test HB"
            opam pin add coq-hierarchy-builder 'https://github.com/math-comp/hierarchy-builder.git' --ignore-constraints-on=coq-elpi -y -j 4
            opam list
          endGroup
```

**Comment by erikmd** [comment]
Hi @gares, thanks for the report! this directly comes from the current implementation of the {{after_script}} interpolation, I'll have a look soon.
