### ISSUE TITLE
python?

### ISSUE THREAD

**Issue by JasonGross** [coq-community/docker-coq-action#53]
python (python3, in particular) is needed for the pretty-timing targets in coq-makefile.  But it does not seem to be installed by default, cf https://github.com/coq-community/run-coq-bug-minimizer/runs/2114450949#step:4:1506.  Could it be added by default?

**Comment by JasonGross** [comment]
(Should this issue be here, or in the docker-coq repo?)

**Comment by erikmd** [comment]
Thanks Jason,

> (Should this issue be here, or in the docker-coq repo?)

→ in the Docker-Coq repo indeed. Closing that issue in favor of https://github.com/coq-community/docker-coq/issues/28
