### ISSUE TITLE
Wish: Export build artifacts

### ISSUE THREAD

**Issue by liyishuai** [coq-community/docker-coq-action#84]
It might be useful to export the build artifacts to outside the docker, and uploading it to GitHub: https://github.com/actions/upload-artifact

For example, Coqdocs: https://github.com/coq-community/coq-ext-lib/blob/b3c05e7070882c774d5761efe4cf181873996fca/.circleci/config.yml#L38-L44

**Comment by erikmd** [comment]
Hi @liyishuai 

This is already possible with a vanilla setup of docker-coq-action,
I had documented this here:

https://github.com/coq-community/docker-coq-action#artifacts

Is it enough for your use case?

**Comment by liyishuai** [comment]
Yes that addresses my issue. Thanks!
