### ISSUE TITLE
`git ls-files` fails with exit code 128 during `opam install --deps-only`

### ISSUE THREAD

**Issue by artagnon** [coq-community/docker-coq-action#87]
Of late, I've been seeing my builds fail for the following reason:

```
+ (script @ line 12) $ opam install --confirm-level=unsafe-yes -j 2 . --deps-only
[368](https://github.com/artagnon/bonak/actions/runs/4838247477/jobs/8622599444#step:4:373)
  Error:  Command "/usr/bin/git ls-files" failed:
[369](https://github.com/artagnon/bonak/actions/runs/4838247477/jobs/8622599444#step:4:374)
  "/usr/bin/git ls-files" exited with code 128
```

I wonder if this is a permissions issue.

**Comment by erikmd** [comment]
> a permissions issue.

Maybe you're right

→ as suggested in https://github.com/coq-community/docker-coq-action#permissions and https://github.com/coq-community/docker-coq-action/issues/86 :

could you try adding this code in your workflow.yml ?

```yaml
      before_install: |
        startGroup "Workaround permission issue"
          sudo chown -R coq:coq .  # <--
        endGroup
        startGroup "Print opam config"
          opam config list; opam repo list; opam list
        endGroup
```

If this work, I'll commit to make this workaround implied and permanent.

**Comment by artagnon** [comment]
Works and the build passes, but the Post Run actions/checkout fails (soft failure):

```
error: could not lock config file .git/config: Permission denied
[14](https://github.com/artagnon/bonak/actions/runs/4838333751/jobs/8622724358#step:8:14)
```

See complete logs here: https://github.com/artagnon/bonak/actions/runs/4838333751/jobs/8622724358

**Comment by erikmd** [comment]
OK! good news.

The remaining warning is standard, as mentioned in https://github.com/coq-community/docker-coq-action/#permissions, just add a final step:

```yaml
  - name: Revert permissions
    # to avoid a warning at cleanup time
    if: ${{ always() }}
    run: sudo chown -R 1001:116 .  # <--
```

**Comment by artagnon** [comment]
Thanks!
